enum CurrencyEnum {
  USD
  EUR
  JPY
}

# Not sure if Status is a good name
type Status {
  epochNumber: Int!
  blockCount: Int!
  latestBlock: Block!,
  decentralization: Float # todo scalar fraction
  price(currency: CurrencyEnum!): Float!
  stakePoolCount: Int
  dataAvailableUpTo: Timestamp!
  currentTime: Timestamp!
}

type Query {
  currentStatus: Status!
}

