# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
test_task_defaults: &test_task_defaults
  steps:
    - checkout:
        path: ~/project

    # Download and cache dependencies
    - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

    - run: yarn install

    - save_cache:
        paths:
          - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}

    - run: yarn test

version: 2
jobs:
  graphql-server:
    docker:
      - image: circleci/node:10.10.0
    working_directory: ~/project/graphql-server
    <<: *test_task_defaults

  frontend:
    docker:
      - image: circleci/node:10.10.0
    working_directory: ~/project/frontend
    <<: *test_task_defaults

workflows:
  version: 2

  test_workflow:
    jobs:
      - graphql-server
      - frontend
