#TODO: these are preliminary

type OwnerPledge {
  declared: AdaAmount
  actual: AdaAmount
}

#TODO: make sure that `stakersCount` does not include owners
type StakePoolSummary {
  performance: Float
  adaStaked: AdaAmount
  rewards: AdaAmount
  keysDelegating: Int
  fullness: Float
  margins: Float
  pledge: AdaAmount
  revenue: Float
  stakersCount: Int
  ownerPledge: OwnerPledge
  usersAdaStaked: AdaAmount
  averageUserStaking: AdaAmount
}

type BootstrapEraStakePool {
  poolHash: ID!
  name: String
  description: String
  summary: StakePoolSummary
  createdAt: Timestamp!
  age: Int!
  website: URL!
}

# TODO: Unify later, for now only used so we can test new "Staking list" section, without
# modifying current endpoints
type MockedStakePool {
  poolHash: ID!
  name: String
  description: String
  summary: StakePoolSummary
  createdAt: Timestamp!
  age: Int!
  website: URL!
}

type PagedStakePoolsResult {
  cursor: String
  hasMore: Boolean!
  stakePools: [BootstrapEraStakePool]!
  totalCount: Int!
}

enum StakePoolSortByEnum {
  REVENUE
  PERFORMANCE
  FULLNESS
  PLEDGE
  MARGINS
  STAKE
}

input PerformanceInterval {
  from: Float!
  to: Float!
}

input StakePoolSearchOptions {
  sortBy: StakePoolSortByEnum!
  searchText: String
  performance: PerformanceInterval
}

type Query {
  stakePoolList(epochNumber: Int): BootstrapEraStakePool!
  pagedStakePoolList(cursor: String, pageSize: Int, searchOptions: StakePoolSearchOptions!): PagedStakePoolsResult!
  stakePool(poolHash: String!, epochNumber: Int): BootstrapEraStakePool,
  stakePools(poolHashes: [String!]!, epochNumber: Int): [BootstrapEraStakePool],
  # TODO: Unify later, for now only used so we can test new "Staking list" section, without
  # modifying current endpoints
  mockedStakePools: [MockedStakePool!]!,
}
