#TODO: these are preliminary
type StakePoolSummary {
  performance: Float
  adaStaked: AdaAmount
  rewards: AdaAmount
  keysDelegating: Int
}

type BootstrapEraStakePool {
  poolHash: ID!
  name: String
  description: String
  summary: StakePoolSummary
}

type Query {
  stakePoolList(epochNumber: Int): [BootstrapEraStakePool]
  stakePool(poolHash: String!, epochNumber: Int): BootstrapEraStakePool
}
