type EpochSummary @cost(complexity: 20) {
  slotCount: Int!
  blocksCreated: Int!
  transactionCount: Int!
  totalAdaSupply: AdaAmount!
  epochFees: AdaAmount!
  totalAdaStaked: AdaAmount!
  stakingRewards: AdaAmount!
  delegatingStakingKeysCount: Int!
  activeStakingPoolCount: Int!
}

type Epoch {
  epochNumber: Int!
  startTime: Timestamp!
  endTime: Timestamp!
  # Todo: make custom 0-1 float scalar type
  progress: Float!
  summary: EpochSummary
}

type Query {
  epoch(epochNumber: Int!): Epoch!
}
