enum AddressTxsFilter {
  SENT
  RECEIVED
  ALL
}

type PagedTransactions {
  cursor: Int
  hasMore: Boolean!
  transactions: [Transaction!]! @cost(multipliers: [10])
  totalCount: Int!
}
type Address @cost(complexity: 10) {
  address58: ID!
  transactionsCount: Int
  # TODO: paging + use cost from pageSize
  transactions(type: AddressTxsFilter!, cursor: Int): PagedTransactions!
  totalAdaSent: AdaAmount
  totalAdaReceived: AdaAmount
  balance: AdaAmount
}

type Query {
  address(address58: String!): Address
}
