type Address {
  address58: ID!
  type: String!
  transactionsCount: Int
  transactions: [Transaction]

  totalAdaSent: AdaAmount
  totalAdaReceived: AdaAmount
  balance: AdaAmount
}

type Query {
  address(address58: String): Address
}
