type Address @cost(complexity: 10) {
  address58: ID!
  type: String!
  transactionsCount: Int
  # TODO: paging + use cost from pageSize
  transactions: [Transaction] @cost(multipliers: [10])

  totalAdaSent: AdaAmount
  totalAdaReceived: AdaAmount
  balance: AdaAmount
}

type Query {
  address(address58: String!): Address
}
